# Generated by Django 5.0.2 on 2025-03-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_player_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='time',
            field=models.CharField(max_length=5),
        ),
    ]
