# Generated by Django 5.0.2 on 2025-04-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_player_remove_leaderboard_questions'),
        ('leaderboard', '0004_alter_leaderboard_time'),
    ]

    operations = [
    ]
